#################################
# PID parameters for pose seeking
#################################

# Maximum value of error integral for all PID controllers
windup_limit: 0.1

# PID gains
x_proportional_gain: 5.0
y_proportional_gain: 5.0
z_proportional_gain: 5.0
x_integral_gain: 0.01
y_integral_gain: 0.01
z_integral_gain: 0.01
x_derivative_gain: 0.0
y_derivative_gain: 0.0
z_derivative_gain: 0.0

angular_proportional_gain: 5.0
angular_integral_gain: 0.01
angular_derivative_gain: 0.0
